/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientRouteImport } from './routes/client'
import { Route as HandoffRouteImport } from './routes/handoff'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as SectionIdRouteImport } from './routes/section.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffRoute = HandoffRouteImport.update({
  id: '/handoff',
  path: '/handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionIdRoute = SectionIdRouteImport.update({
  id: '/section/$id',
  path: '/section/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/client': typeof ClientRoute
  '/handoff': typeof HandoffRoute
  '/interview': typeof InterviewRoute
  '/review': typeof ReviewRoute
  '/summary': typeof SummaryRoute
  '/workspace': typeof WorkspaceRoute
  '/section/$id': typeof SectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/client': typeof ClientRoute
  '/handoff': typeof HandoffRoute
  '/interview': typeof InterviewRoute
  '/review': typeof ReviewRoute
  '/summary': typeof SummaryRoute
  '/workspace': typeof WorkspaceRoute
  '/section/$id': typeof SectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/client': typeof ClientRoute
  '/handoff': typeof HandoffRoute
  '/interview': typeof InterviewRoute
  '/review': typeof ReviewRoute
  '/summary': typeof SummaryRoute
  '/workspace': typeof WorkspaceRoute
  '/section/$id': typeof SectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/client'
    | '/handoff'
    | '/interview'
    | '/review'
    | '/summary'
    | '/workspace'
    | '/section/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/client'
    | '/handoff'
    | '/interview'
    | '/review'
    | '/summary'
    | '/workspace'
    | '/section/$id'
  id:
    | '__root__'
    | '/'
    | '/client'
    | '/handoff'
    | '/interview'
    | '/review'
    | '/summary'
    | '/workspace'
    | '/section/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientRoute: typeof ClientRoute
  HandoffRoute: typeof HandoffRoute
  InterviewRoute: typeof InterviewRoute
  ReviewRoute: typeof ReviewRoute
  SummaryRoute: typeof SummaryRoute
  WorkspaceRoute: typeof WorkspaceRoute
  SectionIdRoute: typeof SectionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoff': {
      id: '/handoff'
      path: '/handoff'
      fullPath: '/handoff'
      preLoaderRoute: typeof HandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/section/$id': {
      id: '/section/$id'
      path: '/section/$id'
      fullPath: '/section/$id'
      preLoaderRoute: typeof SectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientRoute: ClientRoute,
  HandoffRoute: HandoffRoute,
  InterviewRoute: InterviewRoute,
  ReviewRoute: ReviewRoute,
  SummaryRoute: SummaryRoute,
  WorkspaceRoute: WorkspaceRoute,
  SectionIdRoute: SectionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
